version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - mkdir -p package
  build:
    commands:
      - echo "Copying files to package folder"
      - cp lambda_function.py package/
      - cd package
      - zip -r ../deployment.zip .
      - cd ..
artifacts:
  files:
    - deployment.zip
